/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorConfiguracion;
import Controlador.ControladorHorario;
import Controlador.ControladorSnack;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAMAEL
 */
public class Configuracion extends javax.swing.JFrame {

    ControladorConfiguracion cc = new ControladorConfiguracion();
    FondoPanel fondo = new FondoPanel();
    ControladorSnack cs = new ControladorSnack();
    ControladorHorario ch = new ControladorHorario();
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        this.setContentPane(fondo);
        this.setResizable(false);//no redimenciona la ventana
        this.setExtendedState(6);
        initComponents();
        cs.setSnacks(cs.cargarSnack());
        jComboBoxTipoSnack.removeAllItems();
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            if (!(cs.getSnacks().get(i).getEstado_snack()== null)) {
                if (cs.getSnacks().get(i).getEstado_snack() == true) {
                int cont;
                if (jComboBoxTipoSnack.getItemCount() == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                } else {
                    cont=0;
                    for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                        if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                            cont++;
                        }
                        
                    }
                    if(cont==0){
                        jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                    }
                }
            }
            }        
        }
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDescuentoNinio = new javax.swing.JTextField();
        jTextFieldDescuentoAdultoMayor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrecio2D = new javax.swing.JTextField();
        jTextFieldPrecio3D = new javax.swing.JTextField();
        jComboBoxHora3 = new javax.swing.JComboBox<>();
        jComboBoxMinutos1 = new javax.swing.JComboBox<>();
        jComboBoxHora1 = new javax.swing.JComboBox<>();
        jComboBoxMinutos2 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBoxMinutos3 = new javax.swing.JComboBox<>();
        jComboBox23 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldTipoSnack = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxTipoSnack = new javax.swing.JComboBox<>();
        jComboBoxHora4 = new javax.swing.JComboBox<>();
        jComboBoxHora2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESCUENTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRECIOS PELICULAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SNACK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HORARIO DE FUNCIONES ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NIÑO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ADULTO MAYOR:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));
        getContentPane().add(jTextFieldDescuentoNinio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 150, -1));
        getContentPane().add(jTextFieldDescuentoAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("2D:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("3D:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        jTextFieldPrecio2D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecio2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 80, -1));

        jTextFieldPrecio3D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecio3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 80, -1));

        jComboBoxHora3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxHora3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(jComboBoxHora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, 60, -1));

        jComboBoxMinutos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMinutos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBoxMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 60, -1));

        jComboBoxHora1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxHora1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(jComboBoxHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 60, -1));

        jComboBoxMinutos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMinutos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBoxMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, 60, -1));

        jComboBox17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, 60, -1));

        jComboBoxMinutos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMinutos3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBoxMinutos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 570, 60, -1));

        jComboBox23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 570, 60, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Hora 3:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Hora 1:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Hora 2:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Hora");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 50, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Minutos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 470, 70, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Tipo:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Tipo:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));

        jTextFieldTipoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldTipoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 90, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Dar de Baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        jComboBoxTipoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jComboBoxTipoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 110, -1));

        jComboBoxHora4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxHora4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(jComboBoxHora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 60, -1));

        jComboBoxHora2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxHora2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(jComboBoxHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 60, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cs.getSnack();
        cs.getSnack().setTipo_snack(jTextFieldTipoSnack.getText());
        cs.getSnack().setEstado_snack(false);
        cs.registrarSnack(cs.getSnack());
        jComboBoxTipoSnack.removeAllItems();
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            int cont;
            if (jComboBoxTipoSnack.getItemCount() == 0) {
                jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
            } else {
                cont = 0;
                for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                    if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                        cont++;
                    }

                }
                if (cont == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cs.setSnack(cs.traeSnack((String)jComboBoxTipoSnack.getSelectedItem()));
        cs.getSnack().setEstado_snack(false);
        cs.actualizarSnack(cs.getSnack());
        jComboBoxTipoSnack.removeAllItems();
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            int cont;
            if (jComboBoxTipoSnack.getItemCount() == 0) {
                jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
            } else {
                cont = 0;
                for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                    if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                        cont++;
                    }

                }
                if (cont == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                }
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Config.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBoxHora1;
    private javax.swing.JComboBox<String> jComboBoxHora2;
    private javax.swing.JComboBox<String> jComboBoxHora3;
    private javax.swing.JComboBox<String> jComboBoxHora4;
    private javax.swing.JComboBox<String> jComboBoxMinutos1;
    private javax.swing.JComboBox<String> jComboBoxMinutos2;
    private javax.swing.JComboBox<String> jComboBoxMinutos3;
    private javax.swing.JComboBox<String> jComboBoxTipoSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldDescuentoAdultoMayor;
    private javax.swing.JTextField jTextFieldDescuentoNinio;
    private javax.swing.JTextField jTextFieldPrecio2D;
    private javax.swing.JTextField jTextFieldPrecio3D;
    private javax.swing.JTextField jTextFieldTipoSnack;
    // End of variables declaration//GEN-END:variables
}
