/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPelicula;
import Modelo.Pelicula;
import Modelo.Sala;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionPeliculas
     */
    
    DefaultTableModel TablaAdministrarPeliculas;   
    FondoPanel fondo = new FondoPanel();
    ControladorPelicula cp = new ControladorPelicula();
    
    
    public VistaAdministracionPeliculas() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        initComponents();
        this.setResizable(false);//no redimenciona la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAdministracionPelicula = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTituloPelicula = new javax.swing.JTextField();
        jTextFieldAnioPelicula = new javax.swing.JTextField();
        jRadioButtonSubtitulos = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonComedia = new javax.swing.JRadioButton();
        jRadioButtonFiccion = new javax.swing.JRadioButton();
        jRadioButtonTerror = new javax.swing.JRadioButton();
        jRadioButtonRomance = new javax.swing.JRadioButton();
        jRadioButtonAccion = new javax.swing.JRadioButton();
        jRadioButtonDrama = new javax.swing.JRadioButton();
        jRadioButtonInfantilFamiliar = new javax.swing.JRadioButton();
        jTextFieldProveedor = new javax.swing.JTextField();
        jRadioButton2D = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        jRadioButtonEspaniol = new javax.swing.JRadioButton();
        jRadioButtonIngles = new javax.swing.JRadioButton();
        jRadioButtonPortugues = new javax.swing.JRadioButton();
        jRadioButtonFrances = new javax.swing.JRadioButton();
        jPanelPortadaPelicula = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAgregarPortada = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jButtonRegistrarPelicula = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButtonBuscarPelicula = new javax.swing.JButton();
        jButtonMostrarTodosPelicula = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCambiarEstadoPelicula = new javax.swing.JButton();
        jButtonModificarDatosPelicula = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSpinnerDuracionPelicula = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneSinopsisPelicula = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneActoresPelicula = new javax.swing.JTextPane();
        jTextPaneBuscarPelicula = new javax.swing.JTextPane();
        jTextFieldBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministrarPeliculas = new javax.swing.JTable();

        jTableAdministracionPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Película", "Año", "Subtítulos", "Duración", "Género", "Formato", "Idioma", "Estado"
            }
        ));
        jScrollPane5.setViewportView(jTableAdministracionPelicula);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRACIÓN DE PELÍCULAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PELÍCULA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TÍTULO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AÑO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SUBTÍTULOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DURACIÓN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DIRECTOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FORMATO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("IDIOMA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, 20));

        jTextFieldTituloPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTituloPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 270, -1));

        jTextFieldAnioPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAnioPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAnioPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 70, -1));

        jRadioButtonSubtitulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jRadioButtonSubtitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("GÉNERO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jRadioButtonComedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonComedia.setText("Comedia");
        jRadioButtonComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonComediaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jRadioButtonFiccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonFiccion.setText("Ficción");
        getContentPane().add(jRadioButtonFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jRadioButtonTerror.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonTerror.setText("Terror");
        jRadioButtonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTerrorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jRadioButtonRomance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonRomance.setText("Romance");
        jRadioButtonRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRomanceActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jRadioButtonAccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAccion.setText("Acción");
        getContentPane().add(jRadioButtonAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jRadioButtonDrama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDrama.setText("Drama");
        getContentPane().add(jRadioButtonDrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jRadioButtonInfantilFamiliar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonInfantilFamiliar.setText("Infantil/Familiar");
        getContentPane().add(jRadioButtonInfantilFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jTextFieldProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 200, -1));

        jRadioButton2D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2D.setText("2D");
        getContentPane().add(jRadioButton2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, -1));

        jRadioButton3D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3D.setText("3D");
        getContentPane().add(jRadioButton3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        jRadioButtonEspaniol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEspaniol.setText("Español");
        getContentPane().add(jRadioButtonEspaniol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jRadioButtonIngles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonIngles.setText("Inglés");
        getContentPane().add(jRadioButtonIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jRadioButtonPortugues.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonPortugues.setText("Portugués");
        jRadioButtonPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPortuguesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPortugues, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jRadioButtonFrances.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonFrances.setText("Francés");
        jRadioButtonFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrancesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFrances, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jPanelPortadaPelicula.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPortadaPelicula.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Portada");

        javax.swing.GroupLayout jPanelPortadaPeliculaLayout = new javax.swing.GroupLayout(jPanelPortadaPelicula);
        jPanelPortadaPelicula.setLayout(jPanelPortadaPeliculaLayout);
        jPanelPortadaPeliculaLayout.setHorizontalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortadaPeliculaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel11)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelPortadaPeliculaLayout.setVerticalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortadaPeliculaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel11)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPortadaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 200, 120));

        jButtonAgregarPortada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAgregarPortada.setText("Agregar Portada");
        jButtonAgregarPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPortadaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 150, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("PROVEEDOR:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ACTORES:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 20));

        jTextFieldDirector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 270, -1));

        jButtonRegistrarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrarPelicula.setText("Registrar");
        jButtonRegistrarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 100, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SINÓPSIS:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jButtonBuscarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarPelicula.setText("Buscar");
        jButtonBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 90, 30));

        jButtonMostrarTodosPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMostrarTodosPelicula.setText("Mostrar Lista");
        jButtonMostrarTodosPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTodosPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarTodosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, -1, 30));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 502, 1160, 0));

        jButtonCambiarEstadoPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCambiarEstadoPelicula.setText("Cambiar Estado");
        jButtonCambiarEstadoPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarEstadoPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarEstadoPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, -1, 30));

        jButtonModificarDatosPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarDatosPelicula.setText("Modificar Datos");
        jButtonModificarDatosPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDatosPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarDatosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 1160, 30));
        getContentPane().add(jSpinnerDuracionPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 80, 20));

        jTextPaneSinopsisPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jTextPaneSinopsisPelicula);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 440, 70));

        jTextPaneActoresPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneActoresPelicula);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 270, 60));
        getContentPane().add(jTextPaneBuscarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 510, 30));

        jTableAdministrarPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Año", "Género", "Duración", "Subtitulos", "Proveedor", "Formato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAdministrarPeliculas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 860, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAnioPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioPeliculaActionPerformed

    private void jRadioButtonComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonComediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonComediaActionPerformed

    private void jRadioButtonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTerrorActionPerformed

    private void jRadioButtonRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRomanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRomanceActionPerformed

    private void jRadioButtonPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPortuguesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPortuguesActionPerformed

    private void jRadioButtonFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFrancesActionPerformed

    private void jButtonBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPeliculaActionPerformed

    private void jButtonModificarDatosPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDatosPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarDatosPeliculaActionPerformed

    private void jTextFieldProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProveedorActionPerformed

    private void jButtonAgregarPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPortadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPortadaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        MenuAdministrador ma = new MenuAdministrador();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonMostrarTodosPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTodosPeliculaActionPerformed
        VistaListaPeliculas lp = new VistaListaPeliculas();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMostrarTodosPeliculaActionPerformed

    private void jButtonCambiarEstadoPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarEstadoPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarEstadoPeliculaActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonRegistrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPeliculaActionPerformed
        // TODO add your handling code here:
        Pelicula c = new Pelicula();
        c.setTitulo(jTextFieldTituloPelicula.getText());
        c.setAnio(Integer.parseInt(jTextFieldAnioPelicula.getText()));
        c.setSubtitulos(jRadioButtonSubtitulos.getVerifyInputWhenFocusTarget());
        c.setDuracion(jSpinnerDuracionPelicula.getComponentCount());
        c.setGenero(jRadioButtonFiccion.getName() + jRadioButtonAccion.getName() + jRadioButtonTerror.getName());
        c.setProveedor(jTextFieldProveedor.getText());
        c.setIdioma(jRadioButtonEspaniol.getName());
        c.setSinopsis(jTextPaneSinopsisPelicula.getText());
        c.setActores(jTextPaneActoresPelicula.getText());
        c.setDirector(jTextFieldDirector.getText());
        c.setFormato(jRadioButton2D.getName()+jRadioButton3D.getName());
        c.setPortada("direccion");
        
        cp.registrarPelicula(c);    
    }
    private void jButtonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {


    }//GEN-LAST:event_jButtonRegistrarPeliculaActionPerformed

    private void jTextFieldTituloPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministracionPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAgregarPortada;
    private javax.swing.JButton jButtonBuscarPelicula;
    private javax.swing.JButton jButtonCambiarEstadoPelicula;
    private javax.swing.JButton jButtonModificarDatosPelicula;
    private javax.swing.JButton jButtonMostrarTodosPelicula;
    private javax.swing.JButton jButtonRegistrarPelicula;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelPortadaPelicula;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3D;
    private javax.swing.JRadioButton jRadioButtonAccion;
    private javax.swing.JRadioButton jRadioButtonComedia;
    private javax.swing.JRadioButton jRadioButtonDrama;
    private javax.swing.JRadioButton jRadioButtonEspaniol;
    private javax.swing.JRadioButton jRadioButtonFiccion;
    private javax.swing.JRadioButton jRadioButtonFrances;
    private javax.swing.JRadioButton jRadioButtonInfantilFamiliar;
    private javax.swing.JRadioButton jRadioButtonIngles;
    private javax.swing.JRadioButton jRadioButtonPortugues;
    private javax.swing.JRadioButton jRadioButtonRomance;
    private javax.swing.JRadioButton jRadioButtonSubtitulos;
    private javax.swing.JRadioButton jRadioButtonTerror;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerDuracionPelicula;
    private javax.swing.JTable jTableAdministracionPelicula;
    private javax.swing.JTable jTableAdministrarPeliculas;
    private javax.swing.JTextField jTextFieldAnioPelicula;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldProveedor;
    private javax.swing.JTextField jTextFieldTituloPelicula;
    private javax.swing.JTextPane jTextPaneActoresPelicula;
    private javax.swing.JTextPane jTextPaneBuscarPelicula;
    private javax.swing.JTextPane jTextPaneSinopsisPelicula;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM PELICULAS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
