/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaMenuTaquillero extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Inicio
     */
    public VistaMenuTaquillero() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        this.setResizable(false);//no redimenciona la ventana
        initComponents();
        jPanelVenderTicket.setVisible(false);
        jPanelTicketDisponible.setVisible(false);
        jPanelSalir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelVenderTicket = new javax.swing.JPanel();
        jPanelVenderTicketi = new javax.swing.JPanel();
        jLabelImagenVenderTicket = new javax.swing.JLabel();
        jLabelVenderTicket = new javax.swing.JLabel();
        jPanelTicketDisponible = new javax.swing.JPanel();
        jPanelTicketDisponiblei = new javax.swing.JPanel();
        jLabelImagenTicketsDisponibles = new javax.swing.JLabel();
        jLabelTicketsDisponibles = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        jPanelSaliri = new javax.swing.JPanel();
        jLabelImagenSalir = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setEditable(false);
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 250, 70));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 530, 70));

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 130, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usario circulo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 60, 80));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("MI CUENTA ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupaNegra.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, -1, -1));

        jPanelVenderTicket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelVenderTicket.setOpaque(false);
        jPanelVenderTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVenderTicketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelVenderTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelVenderTicketMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVenderTicketLayout = new javax.swing.GroupLayout(jPanelVenderTicket);
        jPanelVenderTicket.setLayout(jPanelVenderTicketLayout);
        jPanelVenderTicketLayout.setHorizontalGroup(
            jPanelVenderTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        jPanelVenderTicketLayout.setVerticalGroup(
            jPanelVenderTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelVenderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 290, 240));

        jPanelVenderTicketi.setOpaque(false);
        jPanelVenderTicketi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelVenderTicketiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelVenderTicketiLayout = new javax.swing.GroupLayout(jPanelVenderTicketi);
        jPanelVenderTicketi.setLayout(jPanelVenderTicketiLayout);
        jPanelVenderTicketiLayout.setHorizontalGroup(
            jPanelVenderTicketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanelVenderTicketiLayout.setVerticalGroup(
            jPanelVenderTicketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelVenderTicketi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 290, 240));

        jLabelImagenVenderTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono VenderTicket.png"))); // NOI18N
        getContentPane().add(jLabelImagenVenderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 210, 200));

        jLabelVenderTicket.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelVenderTicket.setText("VENDER TICKET");
        getContentPane().add(jLabelVenderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        jPanelTicketDisponible.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTicketDisponible.setOpaque(false);
        jPanelTicketDisponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTicketDisponibleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTicketDisponibleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTicketDisponibleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelTicketDisponibleLayout = new javax.swing.GroupLayout(jPanelTicketDisponible);
        jPanelTicketDisponible.setLayout(jPanelTicketDisponibleLayout);
        jPanelTicketDisponibleLayout.setHorizontalGroup(
            jPanelTicketDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanelTicketDisponibleLayout.setVerticalGroup(
            jPanelTicketDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTicketDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, 240));

        jPanelTicketDisponiblei.setOpaque(false);
        jPanelTicketDisponiblei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTicketDisponibleiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelTicketDisponibleiLayout = new javax.swing.GroupLayout(jPanelTicketDisponiblei);
        jPanelTicketDisponiblei.setLayout(jPanelTicketDisponibleiLayout);
        jPanelTicketDisponibleiLayout.setHorizontalGroup(
            jPanelTicketDisponibleiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanelTicketDisponibleiLayout.setVerticalGroup(
            jPanelTicketDisponibleiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTicketDisponiblei, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 250, 240));

        jLabelImagenTicketsDisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono Tickets Disponibles.png"))); // NOI18N
        getContentPane().add(jLabelImagenTicketsDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 160, 150));

        jLabelTicketsDisponibles.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelTicketsDisponibles.setText("TICKETS DISPONIBLES");
        getContentPane().add(jLabelTicketsDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        jPanelSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelSalir.setOpaque(false);
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 280, 240));

        jPanelSaliri.setOpaque(false);
        jPanelSaliri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSaliriMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaliriLayout = new javax.swing.GroupLayout(jPanelSaliri);
        jPanelSaliri.setLayout(jPanelSaliriLayout);
        jPanelSaliriLayout.setHorizontalGroup(
            jPanelSaliriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanelSaliriLayout.setVerticalGroup(
            jPanelSaliriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSaliri, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 327, 280, 240));

        jLabelImagenSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        getContentPane().add(jLabelImagenSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 210, 160));

        jLabelSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelSalir.setText("SALIR");
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPanelVenderTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVenderTicketMouseExited
        jPanelVenderTicket.setVisible(false);
    }//GEN-LAST:event_jPanelVenderTicketMouseExited

    private void jPanelVenderTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVenderTicketMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelVenderTicketMouseEntered

    private void jPanelVenderTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVenderTicketMouseClicked
        VistaVentaTicket vvt = new VistaVentaTicket();
        vvt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelVenderTicketMouseClicked

    private void jPanelVenderTicketiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVenderTicketiMouseEntered
        jPanelVenderTicket.setVisible(true);
    }//GEN-LAST:event_jPanelVenderTicketiMouseEntered

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jPanelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSalirMouseEntered

    private void jPanelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseExited
        jPanelSalir.setVisible(false);
    }//GEN-LAST:event_jPanelSalirMouseExited

    private void jPanelSaliriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSaliriMouseEntered
        jPanelSalir.setVisible(true);
    }//GEN-LAST:event_jPanelSaliriMouseEntered

    private void jPanelTicketDisponibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketDisponibleMouseClicked
        TicketsDisponibles td = new TicketsDisponibles();
        td.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelTicketDisponibleMouseClicked

    private void jPanelTicketDisponibleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketDisponibleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTicketDisponibleMouseEntered

    private void jPanelTicketDisponibleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketDisponibleMouseExited
        jPanelTicketDisponible.setVisible(false);
    }//GEN-LAST:event_jPanelTicketDisponibleMouseExited

    private void jPanelTicketDisponibleiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTicketDisponibleiMouseEntered
        jPanelTicketDisponible.setVisible(true);
    }//GEN-LAST:event_jPanelTicketDisponibleiMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuTaquillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuTaquillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuTaquillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuTaquillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuTaquillero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagenSalir;
    private javax.swing.JLabel jLabelImagenTicketsDisponibles;
    private javax.swing.JLabel jLabelImagenVenderTicket;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTicketsDisponibles;
    private javax.swing.JLabel jLabelVenderTicket;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSaliri;
    private javax.swing.JPanel jPanelTicketDisponible;
    private javax.swing.JPanel jPanelTicketDisponiblei;
    private javax.swing.JPanel jPanelVenderTicket;
    private javax.swing.JPanel jPanelVenderTicketi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/MENU TAQUILLERO.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
