/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaVentaSnack extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();
    public VistaVentaSnack() {
        this.setContentPane(fondo);
        this.setResizable(false);
        this.setExtendedState(6);
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitVentTick = new javax.swing.JLabel();
        jComboBoxSnack = new javax.swing.JComboBox<>();
        jComboBoxTamañoSnack = new javax.swing.JComboBox<>();
        jTextFieldCantidadSnack = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecioSnack = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSnack = new javax.swing.JTable();
        jToggleButtonAceptarSnack = new javax.swing.JToggleButton();
        jToggleButtonPagarSnack = new javax.swing.JToggleButton();
        jTextFieldPrecioTotalSnack = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToggleButtonRegresarSnack = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitVentTick.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitVentTick.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitVentTick.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitVentTick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitVentTick.setText("VENTA DE SNACK");
        getContentPane().add(jLabelTitVentTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 630, 60));

        jComboBoxSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palomitas", "Nachos", "Gaseosa", " " }));
        jComboBoxSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, -1));

        jComboBoxTamañoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTamañoSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        getContentPane().add(jComboBoxTamañoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 130, -1));

        jTextFieldCantidadSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldCantidadSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SNACK:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CANTIDAD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TAMAÑO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jTextFieldPrecioSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecioSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 130, 30));

        jTableSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableSnack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Snack", "Cantidad", "Tamaño", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSnack);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 980, 180));

        jToggleButtonAceptarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonAceptarSnack.setText("ACEPTAR");
        getContentPane().add(jToggleButtonAceptarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 380, 140, 30));

        jToggleButtonPagarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonPagarSnack.setText("PAGAR");
        jToggleButtonPagarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPagarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonPagarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 660, 130, -1));

        jTextFieldPrecioTotalSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecioTotalSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PRECIO TOTAL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 120, 20));

        jToggleButtonRegresarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonRegresarSnack.setText("REGRESAR");
        jToggleButtonRegresarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRegresarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonRegresarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonRegresarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRegresarSnackActionPerformed
        // TODO add your handling code here:
        VistaMenuVendedor vmv = new VistaMenuVendedor();
        vmv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonRegresarSnackActionPerformed

    private void jToggleButtonPagarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPagarSnackActionPerformed
        // TODO add your handling code here:
        Pago p = new Pago(2);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonPagarSnackActionPerformed

    private void jComboBoxSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSnackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVentaSnack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVentaSnack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVentaSnack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVentaSnack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVentaSnack().setVisible(true);
            }
        });
    }
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/VENTA SNACKS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSnack;
    private javax.swing.JComboBox<String> jComboBoxTamañoSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitVentTick;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSnack;
    private javax.swing.JTextField jTextFieldCantidadSnack;
    private javax.swing.JTextField jTextFieldPrecioSnack;
    private javax.swing.JTextField jTextFieldPrecioTotalSnack;
    private javax.swing.JToggleButton jToggleButtonAceptarSnack;
    private javax.swing.JToggleButton jToggleButtonPagarSnack;
    private javax.swing.JToggleButton jToggleButtonRegresarSnack;
    // End of variables declaration//GEN-END:variables
}

