/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorSnack;
import Modelo.Snack;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionSnacks extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionSnacks
     */
    ControladorSnack cs = new ControladorSnack();
    FondoPanel fondo = new FondoPanel();

    public VistaAdministracionSnacks() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        initComponents();
        this.setResizable(false);//no redimenciona la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministracionSnacks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoSnack = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTamanioSnack = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldCantidadSnack = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCantidadSnack1 = new javax.swing.JTextField();
        jPanelImagenSnack = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAgregarImagenSnack = new javax.swing.JButton();
        jButtonDarDeBajaSnack = new javax.swing.JButton();
        jButtonModificarSnack = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAdministracionSnacks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAdministracionSnacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Snack", "Tipo", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableAdministracionSnacks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 393, 760, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRACIÓN DE SNACKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jComboBoxTipoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 155, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TAMAÑO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 30));

        jComboBoxTamanioSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTamanioSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamanioSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTamanioSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 155, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        jTextFieldCantidadSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 101, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jTextFieldCantidadSnack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadSnack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadSnack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadSnack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 101, -1));

        jPanelImagenSnack.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Imagen");

        javax.swing.GroupLayout jPanelImagenSnackLayout = new javax.swing.GroupLayout(jPanelImagenSnack);
        jPanelImagenSnack.setLayout(jPanelImagenSnackLayout);
        jPanelImagenSnackLayout.setHorizontalGroup(
            jPanelImagenSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenSnackLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImagenSnackLayout.setVerticalGroup(
            jPanelImagenSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenSnackLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanelImagenSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 220, -1));

        jButtonAgregarImagenSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAgregarImagenSnack.setText("Agregar imagen");
        jButtonAgregarImagenSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarImagenSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarImagenSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, -1, -1));

        jButtonDarDeBajaSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDarDeBajaSnack.setText("Dar de Baja");
        getContentPane().add(jButtonDarDeBajaSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 110, -1));

        jButtonModificarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarSnack.setText("Modificar");
        jButtonModificarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 110, -1));

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TIPO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoSnackActionPerformed

    private void jComboBoxTamanioSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamanioSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamanioSnackActionPerformed

    private void jTextFieldCantidadSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadSnackActionPerformed

    private void jTextFieldCantidadSnack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadSnack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadSnack1ActionPerformed

    private void jButtonAgregarImagenSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarImagenSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarImagenSnackActionPerformed

    private void jButtonModificarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarSnackActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        MenuAdministrador ma = new MenuAdministrador();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Snack s = new Snack();
        s.setTipo_snack((String) jComboBoxTipoSnack.getSelectedItem());
        s.setCantidad(Integer.parseInt(jTextFieldCantidadSnack1.getText()));
        s.setTamanio((String) jComboBoxTamanioSnack.getSelectedItem());
        s.setPrecio_snack(Double.parseDouble(jTextFieldCantidadSnack.getText()));
        cs.registrarSala(s);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministracionSnacks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarImagenSnack;
    private javax.swing.JButton jButtonDarDeBajaSnack;
    private javax.swing.JButton jButtonModificarSnack;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxTamanioSnack;
    private javax.swing.JComboBox<String> jComboBoxTipoSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelImagenSnack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdministracionSnacks;
    private javax.swing.JTextField jTextFieldCantidadSnack;
    private javax.swing.JTextField jTextFieldCantidadSnack1;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM SNACKS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
