/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorSala;
import Modelo.Funcion;
import Modelo.Sala;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionSalas extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionSalas
     */
    ControladorSala cs = new ControladorSala();
    FondoPanel fondo = new FondoPanel();

    public VistaAdministracionSalas() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        initComponents();
        this.setResizable(false);//no redimenciona la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministracionSalas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCapacidadSala = new javax.swing.JTextField();
        jButtonRegistrarSala = new javax.swing.JButton();
        jButtonCambiarEstadoSala = new javax.swing.JButton();
        jButtonModificarDatosSala = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelNumSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAdministracionSalas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAdministracionSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Sala", "Estado", "Capacidad"
            }
        ));
        jScrollPane1.setViewportView(jTableAdministracionSalas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 750, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRACIÓN DE SALAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Capacidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jTextFieldCapacidadSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCapacidadSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCapacidadSalaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCapacidadSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 130, 30));

        jButtonRegistrarSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrarSala.setText("Registrar");
        jButtonRegistrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarSalaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 110, 30));

        jButtonCambiarEstadoSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCambiarEstadoSala.setText("Cambiar Estado");
        getContentPane().add(jButtonCambiarEstadoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, -1, -1));

        jButtonModificarDatosSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarDatosSala.setText("ModificarDatos");
        getContentPane().add(jButtonModificarDatosSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, 130, -1));

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("N° Sala:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabelNumSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumSala.setText("0");
        getContentPane().add(jLabelNumSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCapacidadSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapacidadSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapacidadSalaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        MenuAdministrador ma = new MenuAdministrador();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonRegistrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarSalaActionPerformed
        // TODO add your handling code here:
        Sala s = new Sala();
        s.setNumeroSala(1);
        s.setCapacidad(Integer.parseInt(jTextFieldCapacidadSala.getText()));
        
        cs.registrarSala(s);
    }//GEN-LAST:event_jButtonRegistrarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministracionSalas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarEstadoSala;
    private javax.swing.JButton jButtonModificarDatosSala;
    private javax.swing.JButton jButtonRegistrarSala;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNumSala;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdministracionSalas;
    private javax.swing.JTextField jTextFieldCapacidadSala;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM SALAS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
