/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionPeliculas
     */
    FondoPanel fondo = new FondoPanel();

    public VistaAdministracionPeliculas() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        initComponents();
        this.setResizable(false);//no redimenciona la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        scrollPaneAdmPelicula = new java.awt.ScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAdministracionPelicula = new javax.swing.JTable();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTituloPelicula = new javax.swing.JTextField();
        jTextFieldAnioPelicula = new javax.swing.JTextField();
        jRadioButtonSubtitulos = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDuracionPelicula = new javax.swing.JTextField();
        jRadioButtonComedia = new javax.swing.JRadioButton();
        jRadioButtonFiccion = new javax.swing.JRadioButton();
        jRadioButtonTerror = new javax.swing.JRadioButton();
        jRadioButtonRomance = new javax.swing.JRadioButton();
        jRadioButtonAccion = new javax.swing.JRadioButton();
        jRadioButtonDrama = new javax.swing.JRadioButton();
        jRadioButtonInfantilFamiliar = new javax.swing.JRadioButton();
        jTextFieldProveedor = new javax.swing.JTextField();
        jRadioButton2D = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        jRadioButtonEspaniol = new javax.swing.JRadioButton();
        jRadioButtonIngles = new javax.swing.JRadioButton();
        jRadioButtonPortugues = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSinopsis = new javax.swing.JTextArea();
        jRadioButtonFrances = new javax.swing.JRadioButton();
        jPanelPortadaPelicula = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAgregarPortada = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaActores = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jButtonRegistrarPelicula = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneBuscarPelicula = new javax.swing.JTextPane();
        jButtonBuscarPelicula = new javax.swing.JButton();
        jButtonMostrarTodosPelicula = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCambiarEstadoPelicula = new javax.swing.JButton();
        jButtonModificarDatosPelicula = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRACIÓN DE PELÍCULAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jTableAdministracionPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Película", "Año", "Subtítulos", "Duración", "Género", "Formato", "Idioma", "Estado"
            }
        ));
        jScrollPane5.setViewportView(jTableAdministracionPelicula);

        scrollPaneAdmPelicula.add(jScrollPane5);

        getContentPane().add(scrollPaneAdmPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 630, 130));

        jButtonRegresar.setText("Regresar");
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, -1, -1));

        jLabel1.setText("PELÍCULA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, 20));

        jLabel3.setText("TÍTULO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setText("AÑO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel5.setText("SUBTÍTULOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 20));

        jLabel6.setText("DURACIÓN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 20));

        jLabel7.setText("DIRECTOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        jLabel8.setText("FORMATO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        jLabel9.setText("IDIOMA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));
        getContentPane().add(jTextFieldTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 270, -1));

        jTextFieldAnioPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAnioPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 70, -1));
        getContentPane().add(jRadioButtonSubtitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel10.setText("GÉNERO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jTextFieldDuracionPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDuracionPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 20));

        jRadioButtonComedia.setText("Comedia");
        jRadioButtonComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonComediaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jRadioButtonFiccion.setText("Ficción");
        getContentPane().add(jRadioButtonFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jRadioButtonTerror.setText("Terror");
        jRadioButtonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTerrorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jRadioButtonRomance.setText("Romance");
        jRadioButtonRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRomanceActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jRadioButtonAccion.setText("Acción");
        getContentPane().add(jRadioButtonAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jRadioButtonDrama.setText("Drama");
        getContentPane().add(jRadioButtonDrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jRadioButtonInfantilFamiliar.setText("Infantil/Familiar");
        getContentPane().add(jRadioButtonInfantilFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));
        getContentPane().add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 200, -1));

        jRadioButton2D.setText("2D");
        getContentPane().add(jRadioButton2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, -1));

        jRadioButton3D.setText("3D");
        getContentPane().add(jRadioButton3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        jRadioButtonEspaniol.setText("Español");
        getContentPane().add(jRadioButtonEspaniol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jRadioButtonIngles.setText("Inglés");
        getContentPane().add(jRadioButtonIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jRadioButtonPortugues.setText("Portugués");
        jRadioButtonPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPortuguesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPortugues, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jTextAreaSinopsis.setColumns(20);
        jTextAreaSinopsis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSinopsis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 410, 50));

        jRadioButtonFrances.setText("Francés");
        jRadioButtonFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrancesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFrances, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        jLabel11.setText("Portada");

        javax.swing.GroupLayout jPanelPortadaPeliculaLayout = new javax.swing.GroupLayout(jPanelPortadaPelicula);
        jPanelPortadaPelicula.setLayout(jPanelPortadaPeliculaLayout);
        jPanelPortadaPeliculaLayout.setHorizontalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortadaPeliculaLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel11)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanelPortadaPeliculaLayout.setVerticalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPortadaPeliculaLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanelPortadaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 220, 120));

        jButtonAgregarPortada.setText("Agregar Portada");
        getContentPane().add(jButtonAgregarPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, -1, -1));

        jLabel12.setText("PROVEEDOR:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jTextAreaActores.setColumns(20);
        jTextAreaActores.setRows(5);
        jScrollPane2.setViewportView(jTextAreaActores);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 270, 50));

        jLabel13.setText("ACTORES:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));
        getContentPane().add(jTextFieldDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 270, -1));

        jButtonRegistrarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrarPelicula.setText("Registrar");
        getContentPane().add(jButtonRegistrarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 440, 100, 30));

        jLabel14.setText("SINÓPSIS:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jScrollPane3.setViewportView(jTextPaneBuscarPelicula);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 330, -1));

        jButtonBuscarPelicula.setText("Buscar");
        jButtonBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, -1));

        jButtonMostrarTodosPelicula.setText("Mostrar Todos");
        getContentPane().add(jButtonMostrarTodosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 502, 1160, 0));

        jButtonCambiarEstadoPelicula.setText("Cambiar Estado");
        getContentPane().add(jButtonCambiarEstadoPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, -1));

        jButtonModificarDatosPelicula.setText("Modificar Datos");
        jButtonModificarDatosPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDatosPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarDatosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 1160, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAnioPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioPeliculaActionPerformed

    private void jTextFieldDuracionPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionPeliculaActionPerformed

    private void jRadioButtonComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonComediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonComediaActionPerformed

    private void jRadioButtonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTerrorActionPerformed

    private void jRadioButtonRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRomanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRomanceActionPerformed

    private void jRadioButtonPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPortuguesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPortuguesActionPerformed

    private void jRadioButtonFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFrancesActionPerformed

    private void jButtonBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPeliculaActionPerformed

    private void jButtonModificarDatosPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDatosPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarDatosPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministracionPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAgregarPortada;
    private javax.swing.JButton jButtonBuscarPelicula;
    private javax.swing.JButton jButtonCambiarEstadoPelicula;
    private javax.swing.JButton jButtonModificarDatosPelicula;
    private javax.swing.JButton jButtonMostrarTodosPelicula;
    private javax.swing.JButton jButtonRegistrarPelicula;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelPortadaPelicula;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3D;
    private javax.swing.JRadioButton jRadioButtonAccion;
    private javax.swing.JRadioButton jRadioButtonComedia;
    private javax.swing.JRadioButton jRadioButtonDrama;
    private javax.swing.JRadioButton jRadioButtonEspaniol;
    private javax.swing.JRadioButton jRadioButtonFiccion;
    private javax.swing.JRadioButton jRadioButtonFrances;
    private javax.swing.JRadioButton jRadioButtonInfantilFamiliar;
    private javax.swing.JRadioButton jRadioButtonIngles;
    private javax.swing.JRadioButton jRadioButtonPortugues;
    private javax.swing.JRadioButton jRadioButtonRomance;
    private javax.swing.JRadioButton jRadioButtonSubtitulos;
    private javax.swing.JRadioButton jRadioButtonTerror;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableAdministracionPelicula;
    private javax.swing.JTextArea jTextAreaActores;
    private javax.swing.JTextArea jTextAreaSinopsis;
    private javax.swing.JTextField jTextFieldAnioPelicula;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldDuracionPelicula;
    private javax.swing.JTextField jTextFieldProveedor;
    private javax.swing.JTextField jTextFieldTituloPelicula;
    private javax.swing.JTextPane jTextPaneBuscarPelicula;
    private java.awt.ScrollPane scrollPaneAdmPelicula;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM PELICULAS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
