/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCuenta;
import Controlador.ControladorUsuario;
import Controlador.placeHolder;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Veronica Estefania
 */
public class VistaCuenta extends javax.swing.JFrame {

    /**
     * Creates new form VistaCuenta
     */
    int id_externo;
    int id_usuario;
    FondoPanel fondo = new FondoPanel();
    ControladorCuenta cc = new ControladorCuenta();
    ControladorUsuario cu = new ControladorUsuario();
    byte[] imagen;
    File archivo;
    FileInputStream entrada;
    JFileChooser seleccionar = new JFileChooser();
    String direccion="";
    
    public VistaCuenta(int id_ex, int id_usr) {
        this.setContentPane(fondo);
        this.setResizable(false);//no redimenciona la ventana
        this.setExtendedState(6);
        initComponents();
        id_externo = id_ex;
        id_usuario = id_usr;
        cargarDatos();
        placeHolder place1 = new placeHolder("Ejm: ¿Que desea buscar?", jTextFieldBuscar);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonGuardarCambios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jButtonEditarImagen1 = new javax.swing.JButton();
        jButtonEditarImagen2 = new javax.swing.JButton();
        jButtonModificarClave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 210, 180));

        jButtonGuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cedula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 380, 40));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 190, -1));

        jLabelApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelApellido.setText("Apellido");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 200, -1));

        jLabelCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCedula.setText("Cedula");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 190, -1));

        jLabelCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCorreo.setText("Correo");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 280, -1));

        jButtonEditarImagen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditarImagen1.setText("Editar Imagen");
        jButtonEditarImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarImagen1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jButtonEditarImagen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditarImagen2.setText("Regresar");
        jButtonEditarImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarImagen2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        jButtonModificarClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarClave.setText("Modificar Clave");
        jButtonModificarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarClaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 60, 40));

        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 131, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefono.setText("Telefono");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 220, -1));

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 131, -1));

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 131, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 131, -1));

        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 131, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        if (id_usuario == 1) {
            cu.setUsuario(cc.getCuenta().getUsu());
            cu.getUsuario().setNombre(jTextFieldNombre.getText());
            cu.getUsuario().setApellido(jTextFieldApellido.getText());
            cu.getUsuario().setCedula(jTextFieldCedula.getText());
            cu.getUsuario().setTelefono(jTextFieldTelefono.getText());
            cu.getUsuario().setCorreo(jTextFieldCorreo.getText());
            cu.actualizarUsuario(cu.getUsuario());
            cc.getCuenta().setUsuario(jTextFieldCedula.getText());
            cc.getCuenta().setClave(cc.getMD5(jTextFieldCedula.getText()));
            cc.getCuenta().setUsu(cu.getUsuario());
            cc.actualizarCuenta(cc.getCuenta());
        } else {
            cu.setUsuario(cc.getCuenta().getUsu());
            cu.getUsuario().setTelefono(jTextFieldTelefono.getText());
            cu.getUsuario().setCorreo(jTextFieldCorreo.getText());
            cu.actualizarUsuario(cu.getUsuario());
        }
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonEditarImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarImagen1ActionPerformed
        if (seleccionar.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
           archivo = seleccionar.getSelectedFile();
           if (archivo.canRead()) {
               if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {
                   direccion=(archivo.getAbsolutePath());
                   imagen = AbrirArchivo(archivo);
                   jLabel6.setIcon(new ImageIcon(imagen));
               } else {
                   JOptionPane.showMessageDialog(null, "Archivo no compatible.");

               }
           }
       }
        cc.getCuenta().getUsu().setFoto(direccion);
        cc.actualizarCuenta(cc.getCuenta());
        
    }//GEN-LAST:event_jButtonEditarImagen1ActionPerformed

    private void jButtonEditarImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarImagen2ActionPerformed
        switch (id_externo) {
            case -1:
                MenuAdministrador ma = new MenuAdministrador();
                ma.setVisible(true);
                break;
            case 0:
                AdmUsuarios au = new AdmUsuarios();
                au.setVisible(true);
                break;
        }
        this.dispose();

    }//GEN-LAST:event_jButtonEditarImagen2ActionPerformed

    private void jButtonModificarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarClaveActionPerformed
        ModificarClave mc = new ModificarClave(id_usuario);
        mc.setVisible(true);
        mc.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonModificarClaveActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void cargarDatos() {
        cc.setCuenta(cc.traerCuenta(id_usuario));
        System.out.println(cc.getCuenta().getUsu().getFoto());
        if(!cc.getCuenta().getUsu().getFoto().isEmpty()){
            imagen = AbrirArchivo(new File(cc.getCuenta().getUsu().getFoto()));
            jLabel6.setIcon(new ImageIcon(imagen));
        }
        
        
        switch (id_externo) {
            case -1:
                jTextFieldNombre.setVisible(false);
                jTextFieldApellido.setVisible(false);
                jTextFieldCedula.setVisible(false);
                jTextFieldTelefono.setVisible(false);
                jTextFieldCorreo.setVisible(false);
                jLabelNombre.setText(cc.getCuenta().getUsu().getNombre());
                jLabelApellido.setText(cc.getCuenta().getUsu().getApellido());
                jLabelCedula.setText(cc.getCuenta().getUsu().getCedula());
                jLabelTelefono.setText(cc.getCuenta().getUsu().getTelefono());
                jLabelCorreo.setText(cc.getCuenta().getUsu().getCorreo());
                jButtonGuardarCambios.setVisible(false);
                break;
            case 0:
                if (id_usuario == 1) {
                    jLabelNombre.setVisible(false);
                    jLabelApellido.setVisible(false);
                    jLabelCedula.setVisible(false);
                    jLabelTelefono.setVisible(false);
                    jLabelCorreo.setVisible(false);
                    jTextFieldNombre.setText(cc.getCuenta().getUsu().getNombre());
                    jTextFieldApellido.setText(cc.getCuenta().getUsu().getApellido());
                    jTextFieldCedula.setText(cc.getCuenta().getUsu().getCedula());
                    jTextFieldTelefono.setText(cc.getCuenta().getUsu().getTelefono());
                    jTextFieldCorreo.setText(cc.getCuenta().getUsu().getCorreo());
                } else {
                    jTextFieldNombre.setVisible(false);
                    jTextFieldApellido.setVisible(false);
                    jTextFieldCedula.setVisible(false);
                    jLabelTelefono.setVisible(false);
                    jLabelCorreo.setVisible(false);
                    jLabelNombre.setText(cc.getCuenta().getUsu().getNombre());
                    jLabelApellido.setText(cc.getCuenta().getUsu().getApellido());
                    jLabelCedula.setText(cc.getCuenta().getUsu().getCedula());
                    jTextFieldTelefono.setText(cc.getCuenta().getUsu().getTelefono());
                    jTextFieldCorreo.setText(cc.getCuenta().getUsu().getCorreo());
                }
                break;

        }
    }

    public byte[] AbrirArchivo(File archivo) {
        byte[] imagen = new byte[1024 * 100];
        try {
            entrada = new FileInputStream(archivo);
            entrada.read(imagen);
        } catch (Exception e) {
        }
        return imagen;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarImagen1;
    private javax.swing.JButton jButtonEditarImagen2;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JButton jButtonModificarClave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Mi cuenta.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
