/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPelicula;
import Modelo.Pelicula;
import Modelo.Sala;
import Controlador.placeHolder;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionPeliculas
     */
    DefaultTableModel TablaAdministrarPeliculas = new DefaultTableModel();
    FondoPanel fondo = new FondoPanel();
    ControladorPelicula cp = new ControladorPelicula();
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    byte[] imagen;
    FileInputStream entrada;
    String direccion = "";

    public VistaAdministracionPeliculas() {
        this.setContentPane(fondo);
        this.setExtendedState(6);

        initComponents();
        placeHolder place1 = new placeHolder("Ejm: Albin y las Ardillas", jTextFieldTituloPelicula);
        place1.setForeground(Color.gray);
        placeHolder place2 = new placeHolder("Ejm: 2007", jTextFieldAnioPelicula);
        placeHolder place3 = new placeHolder("Ejm: El conjuro", jTextFieldBuscar);
        placeHolder place4 = new placeHolder("Ejm: Juan Peres", jTextFieldDirector);
        placeHolder place5 = new placeHolder("Ejm: CINEMAX", jTextFieldProveedor);
        this.setResizable(false);//no redimenciona la ventana
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAdministracionPelicula = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTituloPelicula = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jRadioButtonSubtitulos = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonComedia = new javax.swing.JRadioButton();
        jRadioButtonFiccion = new javax.swing.JRadioButton();
        jRadioButtonTerror = new javax.swing.JRadioButton();
        jRadioButtonRomance = new javax.swing.JRadioButton();
        jRadioButtonAccion = new javax.swing.JRadioButton();
        jRadioButtonDrama = new javax.swing.JRadioButton();
        jRadioButtonInfantilFamiliar = new javax.swing.JRadioButton();
        jTextFieldProveedor = new javax.swing.JTextField();
        jRadioButton2D = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        jRadioButtonEspaniol = new javax.swing.JRadioButton();
        jRadioButtonIngles = new javax.swing.JRadioButton();
        jRadioButtonPortugues = new javax.swing.JRadioButton();
        jRadioButtonFrances = new javax.swing.JRadioButton();
        jPanelPortadaPelicula = new javax.swing.JPanel();
        jLabelPortada = new javax.swing.JLabel();
        jButtonAgregarPortada = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jButtonRegistrarPelicula = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButtonBuscarPelicula = new javax.swing.JButton();
        jButtonMostrarTodosPelicula = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCambiarEstadoPelicula = new javax.swing.JButton();
        jButtonModificarDatosPelicula = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneSinopsisPelicula = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneActoresPelicula = new javax.swing.JTextPane();
        jTextFieldBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministrarPeliculas = new javax.swing.JTable();
        jTextFieldAnioPelicula = new javax.swing.JTextField();

        jTableAdministracionPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Película", "Año", "Subtítulos", "Duración", "Género", "Formato", "Idioma", "Estado"
            }
        ));
        jScrollPane5.setViewportView(jTableAdministracionPelicula);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRACIÓN DE PELÍCULAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PELÍCULA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TÍTULO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AÑO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SUBTÍTULOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DURACIÓN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DIRECTOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FORMATO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("IDIOMA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, 20));

        jTextFieldTituloPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTituloPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 270, -1));

        jTextFieldDuracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 70, -1));

        jRadioButtonSubtitulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jRadioButtonSubtitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("GÉNERO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jRadioButtonComedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonComedia.setText("Comedia");
        jRadioButtonComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonComediaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jRadioButtonFiccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonFiccion.setText("Ficción");
        getContentPane().add(jRadioButtonFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jRadioButtonTerror.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonTerror.setText("Terror");
        jRadioButtonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTerrorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jRadioButtonRomance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonRomance.setText("Romance");
        jRadioButtonRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRomanceActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jRadioButtonAccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAccion.setText("Acción");
        getContentPane().add(jRadioButtonAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jRadioButtonDrama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDrama.setText("Drama");
        getContentPane().add(jRadioButtonDrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jRadioButtonInfantilFamiliar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonInfantilFamiliar.setText("Infantil/Familiar");
        getContentPane().add(jRadioButtonInfantilFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jTextFieldProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 200, -1));

        jRadioButton2D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2D.setText("2D");
        getContentPane().add(jRadioButton2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, -1));

        jRadioButton3D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3D.setText("3D");
        getContentPane().add(jRadioButton3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        jRadioButtonEspaniol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEspaniol.setText("Español");
        getContentPane().add(jRadioButtonEspaniol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jRadioButtonIngles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonIngles.setText("Inglés");
        getContentPane().add(jRadioButtonIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jRadioButtonPortugues.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonPortugues.setText("Portugués");
        jRadioButtonPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPortuguesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPortugues, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jRadioButtonFrances.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonFrances.setText("Francés");
        jRadioButtonFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFrancesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFrances, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jPanelPortadaPelicula.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPortadaPelicula.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPortada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPortada.setText("Portada");

        javax.swing.GroupLayout jPanelPortadaPeliculaLayout = new javax.swing.GroupLayout(jPanelPortadaPelicula);
        jPanelPortadaPelicula.setLayout(jPanelPortadaPeliculaLayout);
        jPanelPortadaPeliculaLayout.setHorizontalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelPortadaPeliculaLayout.setVerticalGroup(
            jPanelPortadaPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPortada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPortadaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 200, 120));

        jButtonAgregarPortada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAgregarPortada.setText("Agregar Portada");
        jButtonAgregarPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPortadaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 150, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("PROVEEDOR:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ACTORES:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 20));

        jTextFieldDirector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 270, -1));

        jButtonRegistrarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrarPelicula.setText("Registrar");
        jButtonRegistrarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 100, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SINÓPSIS:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jButtonBuscarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarPelicula.setText("Buscar");
        jButtonBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 90, 30));

        jButtonMostrarTodosPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMostrarTodosPelicula.setText("Mostrar Lista");
        jButtonMostrarTodosPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTodosPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarTodosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, -1, 30));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 502, 1160, 0));

        jButtonCambiarEstadoPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCambiarEstadoPelicula.setText("Cambiar Estado");
        jButtonCambiarEstadoPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarEstadoPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiarEstadoPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, -1, 30));

        jButtonModificarDatosPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarDatosPelicula.setText("Modificar Datos");
        jButtonModificarDatosPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDatosPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarDatosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 1160, 30));

        jTextPaneSinopsisPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jTextPaneSinopsisPelicula);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 440, 70));

        jTextPaneActoresPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneActoresPelicula);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 270, 60));

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 510, 30));

        jTableAdministrarPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Año", "Director", "Género", "Duración", "Subtitulos", "Formato", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAdministrarPeliculas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 860, 110));

        jTextFieldAnioPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAnioPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAnioPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionActionPerformed

    private void jRadioButtonComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonComediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonComediaActionPerformed

    private void jRadioButtonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTerrorActionPerformed

    private void jRadioButtonRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRomanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRomanceActionPerformed

    private void jRadioButtonPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPortuguesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPortuguesActionPerformed

    private void jRadioButtonFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFrancesActionPerformed

    private void jButtonBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPeliculaActionPerformed

    private void jButtonModificarDatosPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDatosPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarDatosPeliculaActionPerformed

    private void jTextFieldProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProveedorActionPerformed

    private void jButtonAgregarPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPortadaActionPerformed
        //Imagen
        // Abrir archivo
        if (seleccionar.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {
                    direccion = (archivo.getAbsolutePath());
                    System.out.println(direccion);
                    imagen = AbrirArchivo(archivo);
                    Image i = new ImageIcon(imagen).getImage();
                    ImageIcon img = new ImageIcon(i.getScaledInstance(jLabelPortada.getWidth(), jLabelPortada.getHeight(), Image.SCALE_SMOOTH));
                    jLabelPortada.setIcon(img);
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible.");

                }
            }
        }

    }//GEN-LAST:event_jButtonAgregarPortadaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        MenuAdministrador ma = new MenuAdministrador();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonMostrarTodosPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTodosPeliculaActionPerformed
        VistaListaPeliculas lp = new VistaListaPeliculas();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMostrarTodosPeliculaActionPerformed

    private void jButtonCambiarEstadoPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarEstadoPeliculaActionPerformed
        int FilaTable = jTableAdministrarPeliculas.getSelectedRow();
        if (FilaTable >= 0) {

            cp.setPelicula(cp.traePelicula((String) TablaAdministrarPeliculas.getValueAt(FilaTable, 0),
                    (String) TablaAdministrarPeliculas.getValueAt(FilaTable, 2)));

            if (cp.getPelicula().getEstado_pelicula()) {
                cp.getPelicula().setEstado_pelicula(false);
            } else {
                cp.getPelicula().setEstado_pelicula(true);
            }
            cp.actualizarPelicula(cp.getPelicula());
            int var = TablaAdministrarPeliculas.getRowCount();
            for (int i = 0; i < var; i++) {
                TablaAdministrarPeliculas.removeRow(0);
            }
            cp.setPeliculas(cp.cargarPeliculas());
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }

    }//GEN-LAST:event_jButtonCambiarEstadoPeliculaActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonRegistrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPeliculaActionPerformed
        // TODO add your handling code here:
        if ("".equals(direccion)) {
            JOptionPane.showMessageDialog(null, "Ingrese una portada");
        } else {
            String genero = "";
            if (jRadioButtonFiccion.isSelected()) {
                genero = "Ficcion";
            }
            if (jRadioButtonTerror.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Terror";
                } else {
                    genero = "Terror";
                }
            }
            if (jRadioButtonRomance.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Romance";
                } else {
                    genero = "Romance";
                }
            }
            if (jRadioButtonComedia.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Comedia";
                } else {
                    genero = "Comedia";
                }
            }
            if (jRadioButtonAccion.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Accion";
                } else {
                    genero = "Accion";
                }
            }
            if (jRadioButtonDrama.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Drama";
                } else {
                    genero = "Drama";
                }
            }
            if (jRadioButtonInfantilFamiliar.isSelected()) {
                if (!genero.equals("")) {
                    genero += ",Infantil/Familiar";
                } else {
                    genero = "Infantil/Familiar";
                }
            }

            String idioma = "";
            if (jRadioButtonEspaniol.isSelected()) {
                idioma += "Español";
            }
            if (jRadioButtonIngles.isSelected()) {
                if (!idioma.equals("")) {
                    idioma += ",Ingles";
                } else {
                    idioma = "Ingles";
                }
            }
            if (jRadioButtonPortugues.isSelected()) {
                if (!idioma.equals("")) {
                    idioma += ",Portugues";
                } else {
                    idioma = "Portugues";
                }
            }
            if (jRadioButtonFrances.isSelected()) {
                if (!idioma.equals("")) {
                    idioma += ",Frances";
                } else {
                    idioma = "Frances";
                }
            }
            cp.getPelicula();
            cp.getPelicula().setTitulo(jTextFieldTituloPelicula.getText());
            cp.getPelicula().setAnio(Integer.parseInt(jTextFieldAnioPelicula.getText()));
            cp.getPelicula().setSubtitulos(jRadioButtonSubtitulos.isSelected());
            cp.getPelicula().setDuracion(Integer.parseInt(jTextFieldDuracion.getText()));
            cp.getPelicula().setGenero(genero);
            cp.getPelicula().setProveedor(jTextFieldProveedor.getText());
            cp.getPelicula().setIdioma(idioma);
            cp.getPelicula().setSinopsis(jTextPaneSinopsisPelicula.getText());
            cp.getPelicula().setActores(jTextPaneActoresPelicula.getText());
            cp.getPelicula().setDirector(jTextFieldDirector.getText());
            cp.getPelicula().setFormato2D(jRadioButton2D.isSelected());
            cp.getPelicula().setFormato3D(jRadioButton3D.isSelected());
            cp.getPelicula().setPortada(direccion);
            cp.getPelicula().setEstado_pelicula(true);
            cp.registrarPelicula(cp.getPelicula());
            int var = TablaAdministrarPeliculas.getRowCount();
            for (int i = 0; i < var; i++) {
                TablaAdministrarPeliculas.removeRow(0);
            }
            cargarTabla();
        }

    }

    public byte[] AbrirArchivo(File archivo) {
        byte[] imagen = new byte[1024 * 100];
        try {
            entrada = new FileInputStream(archivo);
            entrada.read(imagen);
        } catch (Exception e) {
        }
        return imagen;
    }

    private void jButtonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {


    }//GEN-LAST:event_jButtonRegistrarPeliculaActionPerformed

    private void jTextFieldTituloPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloPeliculaActionPerformed

    private void jTextFieldAnioPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministracionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministracionPeliculas().setVisible(true);
            }
        });
    }

    private void cargarTabla() {
        cp.setPeliculas(cp.cargarPeliculas());
        TablaAdministrarPeliculas = (DefaultTableModel) jTableAdministrarPeliculas.getModel();
        for (int i = 0; i < cp.getPeliculas().size(); i++) {                                    //Bucle que recorre la consulta obtenida
            String estado;
            String sub;
            if (cp.getPeliculas().get(i).getEstado_pelicula() == true) {
                estado = "Disponible";
            } else {
                estado = "No Disponible";
            }
            if (cp.getPeliculas().get(i).getSubtitulos() == true) {
                sub = "SI";
            } else {
                sub = "NO";
            }
            String formato = "";
            if (cp.getPeliculas().get(i).isFormato2D()) {
                if (cp.getPeliculas().get(i).isFormato3D()) {
                    formato = "2D, 3D";
                } else {
                    formato = "2D";
                }
            }
            if (cp.getPeliculas().get(i).isFormato3D()) {
                if (cp.getPeliculas().get(i).isFormato2D()) {
                    formato = "2D, 3D";
                } else {
                    formato = "3D";
                }
            }
            TablaAdministrarPeliculas.addRow(new Object[]{
                cp.getPeliculas().get(i).getTitulo(), cp.getPeliculas().get(i).getAnio(), cp.getPeliculas().get(i).getDirector(),
                cp.getPeliculas().get(i).getGenero(), cp.getPeliculas().get(i).getDuracion(), sub, formato, estado
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAgregarPortada;
    private javax.swing.JButton jButtonBuscarPelicula;
    private javax.swing.JButton jButtonCambiarEstadoPelicula;
    private javax.swing.JButton jButtonModificarDatosPelicula;
    private javax.swing.JButton jButtonMostrarTodosPelicula;
    private javax.swing.JButton jButtonRegistrarPelicula;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JPanel jPanelPortadaPelicula;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3D;
    private javax.swing.JRadioButton jRadioButtonAccion;
    private javax.swing.JRadioButton jRadioButtonComedia;
    private javax.swing.JRadioButton jRadioButtonDrama;
    private javax.swing.JRadioButton jRadioButtonEspaniol;
    private javax.swing.JRadioButton jRadioButtonFiccion;
    private javax.swing.JRadioButton jRadioButtonFrances;
    private javax.swing.JRadioButton jRadioButtonInfantilFamiliar;
    private javax.swing.JRadioButton jRadioButtonIngles;
    private javax.swing.JRadioButton jRadioButtonPortugues;
    private javax.swing.JRadioButton jRadioButtonRomance;
    private javax.swing.JRadioButton jRadioButtonSubtitulos;
    private javax.swing.JRadioButton jRadioButtonTerror;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableAdministracionPelicula;
    private javax.swing.JTable jTableAdministrarPeliculas;
    private javax.swing.JTextField jTextFieldAnioPelicula;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldProveedor;
    private javax.swing.JTextField jTextFieldTituloPelicula;
    private javax.swing.JTextPane jTextPaneActoresPelicula;
    private javax.swing.JTextPane jTextPaneSinopsisPelicula;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM PELICULAS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
