/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaMenuVendedor extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Inicio
     */
    public VistaMenuVendedor() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        this.setResizable(false);//no redimenciona la ventana
        initComponents();
        jPanelSnack.setVisible(false);
        jPanelListaSnack.setVisible(false);
        jPanelSalir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanelSnack = new javax.swing.JPanel();
        jPanelSnacki = new javax.swing.JPanel();
        jPanelListaSnack = new javax.swing.JPanel();
        jPanelListaSnacki = new javax.swing.JPanel();
        jPanelSalir = new javax.swing.JPanel();
        jPanelSaliri = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 530, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usario circulo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 60, 80));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("MI CUENTA ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 120, 70));

        jTextField3.setEditable(false);
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 250, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupaNegra.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, -1, -1));

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 130, 70));

        jPanelSnack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelSnack.setOpaque(false);
        jPanelSnack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSnackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSnackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSnackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSnackLayout = new javax.swing.GroupLayout(jPanelSnack);
        jPanelSnack.setLayout(jPanelSnackLayout);
        jPanelSnackLayout.setHorizontalGroup(
            jPanelSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanelSnackLayout.setVerticalGroup(
            jPanelSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 250, 220));

        jPanelSnacki.setOpaque(false);
        jPanelSnacki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSnackiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelSnackiLayout = new javax.swing.GroupLayout(jPanelSnacki);
        jPanelSnacki.setLayout(jPanelSnackiLayout);
        jPanelSnackiLayout.setHorizontalGroup(
            jPanelSnackiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanelSnackiLayout.setVerticalGroup(
            jPanelSnackiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSnacki, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 350, 260, 220));

        jPanelListaSnack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelListaSnack.setOpaque(false);
        jPanelListaSnack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelListaSnackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelListaSnackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelListaSnackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaSnackLayout = new javax.swing.GroupLayout(jPanelListaSnack);
        jPanelListaSnack.setLayout(jPanelListaSnackLayout);
        jPanelListaSnackLayout.setHorizontalGroup(
            jPanelListaSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanelListaSnackLayout.setVerticalGroup(
            jPanelListaSnackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelListaSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 260, 220));

        jPanelListaSnacki.setOpaque(false);
        jPanelListaSnacki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelListaSnackiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaSnackiLayout = new javax.swing.GroupLayout(jPanelListaSnacki);
        jPanelListaSnacki.setLayout(jPanelListaSnackiLayout);
        jPanelListaSnackiLayout.setHorizontalGroup(
            jPanelListaSnackiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanelListaSnackiLayout.setVerticalGroup(
            jPanelListaSnackiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelListaSnacki, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 350, 260, 220));

        jPanelSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelSalir.setOpaque(false);
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 260, 220));

        jPanelSaliri.setOpaque(false);
        jPanelSaliri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSaliriMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaliriLayout = new javax.swing.GroupLayout(jPanelSaliri);
        jPanelSaliri.setLayout(jPanelSaliriLayout);
        jPanelSaliriLayout.setHorizontalGroup(
            jPanelSaliriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanelSaliriLayout.setVerticalGroup(
            jPanelSaliriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSaliri, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 350, 260, 220));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/snacks.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 160));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel14.setText("VENDER SNACK");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono ListaSnacks.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 160, 150));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel15.setText("LISTA SNACKS");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, 210, 180));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setText("SALIR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPanelSnackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSnackMouseClicked
//        VistaVentaSnack vvs = new VistaVentaSnack();
//        vvs.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jPanelSnackMouseClicked

    private void jPanelListaSnackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListaSnackMouseClicked
//        VistaListaSnack vls = new VistaListaSnack();
//        vls.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jPanelListaSnackMouseClicked

    private void jPanelListaSnackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListaSnackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelListaSnackMouseEntered

    private void jPanelSnackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSnackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSnackMouseEntered

    private void jPanelSnackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSnackMouseExited
        jPanelSnack.setVisible(false);
    }//GEN-LAST:event_jPanelSnackMouseExited

    private void jPanelListaSnackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListaSnackMouseExited
        jPanelListaSnack.setVisible(false);
    }//GEN-LAST:event_jPanelListaSnackMouseExited

    private void jPanelSnackiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSnackiMouseEntered
        jPanelSnack.setVisible(true);
    }//GEN-LAST:event_jPanelSnackiMouseEntered

    private void jPanelListaSnackiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListaSnackiMouseEntered
        jPanelListaSnack.setVisible(true);
    }//GEN-LAST:event_jPanelListaSnackiMouseEntered

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jPanelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseExited
        jPanelSalir.setVisible(false);
    }//GEN-LAST:event_jPanelSalirMouseExited

    private void jPanelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSalirMouseEntered

    private void jPanelSaliriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSaliriMouseEntered
        jPanelSalir.setVisible(true);
    }//GEN-LAST:event_jPanelSaliriMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelListaSnack;
    private javax.swing.JPanel jPanelListaSnacki;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSaliri;
    private javax.swing.JPanel jPanelSnack;
    private javax.swing.JPanel jPanelSnacki;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/MENU VENDEDOR.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
