/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorSnack;
import Controlador.placeHolder;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaAdministracionSnacks extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministracionSnacks
     */
    ControladorSnack cs = new ControladorSnack();
    FondoPanel fondo = new FondoPanel();
    DefaultTableModel TablaSnacks; //Codigo que crea el modelo de la tabla

    public VistaAdministracionSnacks() {
        this.setContentPane(fondo);
        this.setExtendedState(6);
        //placeHolder place1 = new placeHolder("Ejm: Carolina", jTextFieldPrecioSnack);
        //placeHolder place2 = new placeHolder("Ejm: Paredes", jTextFieldCantidadSnack1);
        initComponents();
        jButtonModificarSnack1.setVisible(false);
        this.setResizable(false);//no redimenciona la ventana
        cs.setSnacks(cs.cargarSnack());
        jComboBoxTipoSnack.removeAllItems();
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            int cont;
            if (jComboBoxTipoSnack.getItemCount() == 0) {
                jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
            } else {
                cont = 0;
                for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                    if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                        cont++;
                    }

                }
                if (cont == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                }
            }

        }
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministracionSnacks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoSnack = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTamanioSnack = new javax.swing.JComboBox<>();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonDarDeBajaSnack = new javax.swing.JButton();
        jButtonModificarSnack = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecioSnack = new javax.swing.JTextField();
        jButtonModificarSnack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAdministracionSnacks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAdministracionSnacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Snack", "Tamaño", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableAdministracionSnacks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 393, 760, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRACIÓN DE SNACKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jComboBoxTipoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 155, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CANTIDAD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 30));

        jComboBoxTamanioSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTamanioSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        jComboBoxTamanioSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamanioSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTamanioSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 155, -1));

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        jTextFieldCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jButtonDarDeBajaSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDarDeBajaSnack.setText("Dar de Baja");
        getContentPane().add(jButtonDarDeBajaSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 110, -1));

        jButtonModificarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarSnack.setText("Modificar");
        jButtonModificarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 110, -1));

        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TIPO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TAMAÑO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 30));

        jTextFieldPrecioSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrecioSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecioSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 101, -1));

        jButtonModificarSnack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarSnack1.setText("Aceptar");
        jButtonModificarSnack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSnack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarSnack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoSnackActionPerformed

    private void jComboBoxTamanioSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamanioSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamanioSnackActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jButtonModificarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSnackActionPerformed
        int FilaTable = jTableAdministracionSnacks.getSelectedRow();
        if (FilaTable >= 0) {
            jButtonModificarSnack1.setVisible(true);
            jButtonRegistrar.setVisible(false);
            cs.setSnack(cs.traeSnack((String)TablaSnacks.getValueAt(FilaTable, 0), (String)TablaSnacks.getValueAt(FilaTable, 1)));
            jComboBoxTipoSnack.removeAllItems();
            jComboBoxTipoSnack.addItem(cs.getSnack().getTipo_snack());
            jComboBoxTamanioSnack.removeAllItems();
            jComboBoxTamanioSnack.addItem(cs.getSnack().getTamanio());
            jTextFieldCantidad.setText(String.valueOf(cs.getSnack().getCantidad()));
            jTextFieldPrecioSnack.setText(String.valueOf(cs.getSnack().getPrecio_snack()));
        }
    }//GEN-LAST:event_jButtonModificarSnackActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        MenuAdministrador ma = new MenuAdministrador();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        cs.getSnacks();
        cs.setSnacks(cs.cargarSnack());
        int cont = 0;
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            if (((String) jComboBoxTipoSnack.getSelectedItem()).equals(cs.getSnacks().get(i).getTipo_snack())) {
                cs.setSnack(cs.traerSnack(cs.getSnacks().get(i).getId_snack()));
                if (cs.getSnack().getPrecio_snack() == 0) {
                    cont++;
                    break;
                }
            }
        }
        if (cont == 0) {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            if (cs.getSnack().getId_snack() == 0) {
                cs.getSnack().setTipo_snack((String) jComboBoxTipoSnack.getSelectedItem());
                cs.getSnack().setTamanio((String) jComboBoxTamanioSnack.getSelectedItem());
                cs.getSnack().setPrecio_snack(Double.parseDouble(jTextFieldCantidad.getText()));
                cs.getSnack().setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
                cs.getSnack().setEstado_snack(true);
                cs.registrarSnack(cs.getSnack());
            } else {
                JOptionPane.showMessageDialog(null, "El snack ya ha sido creado anteriormente");
            }
        } else {
            cs.getSnack().setTipo_snack((String) jComboBoxTipoSnack.getSelectedItem());
            cs.getSnack().setTamanio((String) jComboBoxTamanioSnack.getSelectedItem());
            cs.getSnack().setPrecio_snack(Double.parseDouble(jTextFieldCantidad.getText()));
            cs.getSnack().setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            cs.getSnack().setEstado_snack(true);
            cs.actualizarSnack(cs.getSnack());
        }


    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFieldPrecioSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioSnackActionPerformed

    private void jButtonModificarSnack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSnack1ActionPerformed
        cs.setSnack(cs.traeSnack((String)jComboBoxTipoSnack.getSelectedItem(),(String) jComboBoxTamanioSnack.getSelectedItem()));
        cs.getSnack().setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        cs.getSnack().setPrecio_snack(Double.parseDouble(jTextFieldPrecioSnack.getText()));
        cs.actualizarSnack(cs.getSnack());
        jButtonRegistrar.setVisible(true);
        jButtonModificarSnack1.setVisible(false);
        jComboBoxTipoSnack.removeAllItems();
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            int cont;
            if (jComboBoxTipoSnack.getItemCount() == 0) {
                jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
            } else {
                cont = 0;
                for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                    if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                        cont++;
                    }

                }
                if (cont == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                }
            }

        }
        jComboBoxTamanioSnack.removeAllItems();
        jComboBoxTamanioSnack.addItem("Pequeño");
        jComboBoxTamanioSnack.addItem("Mediano");
        jComboBoxTamanioSnack.addItem("Grande");
        
        
    }//GEN-LAST:event_jButtonModificarSnack1ActionPerformed

    private void cargarTabla() {
        TablaSnacks = (DefaultTableModel) jTableAdministracionSnacks.getModel();
        for (int i = 0; i < cs.getSnacks().size(); i++) {                                    //Bucle que recorre la consulta obtenida
            if (cs.getSnacks().get(i).getEstado_snack() == true) {
                TablaSnacks.addRow(new Object[]{cs.getSnacks().get(i).getTipo_snack(), cs.getSnacks().get(i).getTamanio(),
                    cs.getSnacks().get(i).getCantidad(), cs.getSnacks().get(i).getPrecio_snack()});
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDarDeBajaSnack;
    private javax.swing.JButton jButtonModificarSnack;
    private javax.swing.JButton jButtonModificarSnack1;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxTamanioSnack;
    private javax.swing.JComboBox<String> jComboBoxTipoSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdministracionSnacks;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldPrecioSnack;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ADM SNACKS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
