/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorSnack;
import Controlador.ControladorVentaSnack;
import Controlador.placeHolder;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Victor Ayora, Geovanny Poma, Veronica Placencia, Azucena Toledo
 */
public class VistaVentaSnack extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    ControladorSnack cs = new ControladorSnack();
    DefaultTableModel TablaSnacks; //Codigo que crea el modelo de la tabla
    public static ControladorVentaSnack cvs = new ControladorVentaSnack();
    public static Double precio;
    public static List<Integer> cantidades = new ArrayList();
            
    public VistaVentaSnack() {
        this.setContentPane(fondo);
        this.setResizable(false);
        this.setExtendedState(6);
        initComponents();
        cvs = new ControladorVentaSnack();
        placeHolder place1 = new placeHolder("Ejm: 20", jTextFieldCantidadSnack);
        cs.setSnacks(cs.cargarSnack());
        jComboBoxTipoSnack.removeAllItems();
        
        for (int i = 0; i < cs.getSnacks().size(); i++) {
            if (cs.getSnacks().get(i).getEstado_snack() == true) {
                int cont;
                if (jComboBoxTipoSnack.getItemCount() == 0) {
                    jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                } else {
                    cont = 0;
                    for (int j = 0; j < jComboBoxTipoSnack.getItemCount(); j++) {
                        if (jComboBoxTipoSnack.getItemAt(j).equals(cs.getSnacks().get(i).getTipo_snack())) {
                            cont++;
                        }

                    }
                    if (cont == 0) {
                        jComboBoxTipoSnack.addItem(cs.getSnacks().get(i).getTipo_snack());
                    }
                }
            }
        }
        cvs.getVs();
        cvs.getVs().getSnacks();
        TablaSnacks = (DefaultTableModel) jTableSnack.getModel();
        cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
        jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitVentTick = new javax.swing.JLabel();
        jComboBoxTipoSnack = new javax.swing.JComboBox<>();
        jComboBoxTamanioSnack = new javax.swing.JComboBox<>();
        jTextFieldCantidadSnack = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSnack = new javax.swing.JTable();
        jToggleButtonAceptarSnack = new javax.swing.JToggleButton();
        jToggleButtonPagarSnack = new javax.swing.JToggleButton();
        jTextFieldPrecioTotalSnack = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToggleButtonRegresarSnack = new javax.swing.JToggleButton();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitVentTick.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitVentTick.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitVentTick.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitVentTick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitVentTick.setText("VENTA DE SNACK");
        getContentPane().add(jLabelTitVentTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 630, 60));

        jComboBoxTipoSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBoxTipoSnack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoSnackMouseClicked(evt);
            }
        });
        jComboBoxTipoSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, -1));

        jComboBoxTamanioSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTamanioSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        jComboBoxTamanioSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamanioSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTamanioSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 130, -1));

        jTextFieldCantidadSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadSnack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldCantidadSnackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldCantidadSnackMouseExited(evt);
            }
        });
        jTextFieldCantidadSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SNACK:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CANTIDAD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TAMAÑO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jTableSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableSnack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Snack", "Tamaño", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSnack);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 980, 180));

        jToggleButtonAceptarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonAceptarSnack.setText("ACEPTAR");
        jToggleButtonAceptarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAceptarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonAceptarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 380, 140, 30));

        jToggleButtonPagarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonPagarSnack.setText("PAGAR");
        jToggleButtonPagarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPagarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonPagarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 660, 130, -1));

        jTextFieldPrecioTotalSnack.setEditable(false);
        jTextFieldPrecioTotalSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecioTotalSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PRECIO TOTAL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 120, 20));

        jToggleButtonRegresarSnack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButtonRegresarSnack.setText("REGRESAR");
        jToggleButtonRegresarSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRegresarSnackActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonRegresarSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 120, -1));

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecio.setText("0.00 $");
        getContentPane().add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jLabelStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStock.setText("STOCK: ");
        getContentPane().add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonRegresarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRegresarSnackActionPerformed
        // TODO add your handling code here:
        VistaMenuVendedor vmv = new VistaMenuVendedor();
        vmv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonRegresarSnackActionPerformed

    private void jToggleButtonPagarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPagarSnackActionPerformed
        // TODO add your handling code here:
        Pago p = new Pago(2);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonPagarSnackActionPerformed

    private void jComboBoxTipoSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoSnackActionPerformed
        //se mostrara el precio
        if (jTextFieldCantidadSnack.getText().equals("")) {
        } else {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            jLabelPrecio.setText(String.valueOf(cs.getSnack().getPrecio_snack() * (Double.parseDouble(jTextFieldCantidadSnack.getText()))));
            jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));
        }
    }//GEN-LAST:event_jComboBoxTipoSnackActionPerformed

    private void jToggleButtonAceptarSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAceptarSnackActionPerformed
        if (!(jTextFieldCantidadSnack.getText().equals(""))) {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            if (Integer.parseInt(jTextFieldCantidadSnack.getText()) <= cs.getSnack().getCantidad()) {
                cantidades.add(Integer.parseInt(jTextFieldCantidadSnack.getText()));
                cs.getSnack().setCantidad(cs.getSnack().getCantidad()-(Integer.parseInt(jTextFieldCantidadSnack.getText())));
                jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));
                cvs.getVs().getSnacks().add(cs.getSnack());
                
                cs.setSnacks(cvs.getVs().getSnacks());
                int var = TablaSnacks.getRowCount();
                for (int i = 0; i < var; i++) {
                    TablaSnacks.removeRow(0);
                }
                cargarTabla();
                precio=0.0;
                for(int i=0;i<cvs.getVs().getSnacks().size();i++){
                    precio+=cvs.getVs().getSnacks().get(i).getPrecio_snack();
                }
                jTextFieldPrecioTotalSnack.setText(String.valueOf(precio));
            } else {
                JOptionPane.showMessageDialog(null, "No hay suficiente stock");
            }
        }
    }//GEN-LAST:event_jToggleButtonAceptarSnackActionPerformed

    private void jTextFieldCantidadSnackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCantidadSnackMouseEntered


    }//GEN-LAST:event_jTextFieldCantidadSnackMouseEntered

    private void jComboBoxTipoSnackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoSnackMouseClicked

    }//GEN-LAST:event_jComboBoxTipoSnackMouseClicked

    private void jComboBoxTamanioSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamanioSnackActionPerformed
        //se mostrara el precio
        if (!(jTextFieldCantidadSnack.getText().equals(""))) {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            jLabelPrecio.setText(String.valueOf(cs.getSnack().getPrecio_snack() * (Double.parseDouble(jTextFieldCantidadSnack.getText()))));
            jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));
        }
    }//GEN-LAST:event_jComboBoxTamanioSnackActionPerformed

    private void jTextFieldCantidadSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadSnackActionPerformed
        //se mostrara el precio
        if (!(jTextFieldCantidadSnack.getText().equals(""))) {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            jLabelPrecio.setText(String.valueOf(cs.getSnack().getPrecio_snack() * (Double.parseDouble(jTextFieldCantidadSnack.getText()))));
            jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));       
        }
    }//GEN-LAST:event_jTextFieldCantidadSnackActionPerformed

    private void jTextFieldCantidadSnackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCantidadSnackMouseExited
        //se mostrara el precio
        if (!(jTextFieldCantidadSnack.getText().equals(""))) {
            cs.setSnack(cs.traeSnack((String) jComboBoxTipoSnack.getSelectedItem(), (String) jComboBoxTamanioSnack.getSelectedItem()));
            jLabelPrecio.setText(String.valueOf(cs.getSnack().getPrecio_snack() * (Double.parseDouble(jTextFieldCantidadSnack.getText()))));
            jLabelStock.setText("Stock: "+String.valueOf(cs.getSnack().getCantidad()));       
        }
    }//GEN-LAST:event_jTextFieldCantidadSnackMouseExited

    private void cargarTabla() {
        for (int i = 0; i < cs.getSnacks().size(); i++) {                                    //Bucle que recorre la consulta obtenida
            if (cs.getSnacks().get(i).getEstado_snack() == true) {
                TablaSnacks.addRow(new Object[]{cs.getSnacks().get(i).getTipo_snack(), cs.getSnacks().get(i).getTamanio(),
                    Integer.parseInt(jTextFieldCantidadSnack.getText()), cs.getSnacks().get(i).getPrecio_snack()});
            }

        }
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/VENTA SNACKS.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxTamanioSnack;
    private javax.swing.JComboBox<String> jComboBoxTipoSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTitVentTick;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSnack;
    private javax.swing.JTextField jTextFieldCantidadSnack;
    private javax.swing.JTextField jTextFieldPrecioTotalSnack;
    private javax.swing.JToggleButton jToggleButtonAceptarSnack;
    private javax.swing.JToggleButton jToggleButtonPagarSnack;
    private javax.swing.JToggleButton jToggleButtonRegresarSnack;
    // End of variables declaration//GEN-END:variables
}
